FROM wesnoth/wesnoth:msys2-base

RUN pacman -S --noconfirm scons mingw-w64-gcc pkg-config python-pefile expect nsis git

RUN pacman-cross -S --noconfirm \
    mingw-w64-x86_64-boost \
    mingw-w64-x86_64-sdl3 \
    mingw-w64-x86_64-sdl3-image \
    mingw-w64-x86_64-sdl3-mixer \
    mingw-w64-x86_64-pango \
    mingw-w64-x86_64-curl-winssl

#symlink for compatibility with previous Dockerfiles
RUN ln -s /msys64 /windows
