name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  macos-intel-release:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.20'

      - name: Cache object files
        id: macos-cache
        uses: actions/cache@v2
        with:
          path: |
            /Users/runner/vcpkg
            /Users/runner/work/wesnoth/wesnoth/vcpkg_installed
            /Users/runner/build-cache
          key: M010

      - name: Build vcpkg
        run: |
          ./.github/workflows/ci-scripts/get_vcpkg.sh

      - name: Build code
        run: |
          ./.github/workflows/ci-scripts/macos_compile.sh

      - name: Make dmg
        run: |
          ./.github/workflows/ci-scripts/macos_dmg.sh

      - name: WML unit tests
        run: |
          ./run_wml_tests -g -c -t 60 -p /Users/runner/work/wesnoth/wesnoth/Release/wesnoth.app/Contents/MacOS/wesnoth

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: app bundle
          path: |
            /Users/runner/work/wesnoth/wesnoth/Wesnoth_Release.dmg
