name: CI

on:
  push:
    branches: [ 1.14 ]
  pull_request:
    branches: [ 1.14 ]
  workflow_dispatch:

jobs:
  ubuntu-1604-scons-gcc-release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Ubuntu 1604
        run: |
          export BRANCH=master
          export IMAGE=1604
          export NLS=false
          export TOOL=scons
          export CC=gcc
          export CXX=g++
          export CXX_STD=11
          export CFG=release
          export LTO=false
          export CACHE_DIR=/home/wesnoth-travis/build
          ./.github/workflows/ci-scripts/ubuntu.sh

  ubuntu-1604-scons-clang-debug:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Ubuntu 1604
        run: |
          export BRANCH=master
          export IMAGE=1604
          export NLS=false
          export TOOL=scons
          export CC=clang
          export CXX=clang++
          export CXX_STD=11
          export CFG=debug
          export LTO=false
          export CACHE_DIR=/home/wesnoth-travis/build
          ./.github/workflows/ci-scripts/ubuntu.sh master

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Ubuntu-Clang-Debug
          path: |
            ~/build-cache/wesnoth
            ~/build-cache/wesnothd

  ubuntu-1604-cmake-clang-debug:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Ubuntu 1604
        run: |
          export BRANCH=master
          export IMAGE=1604
          export NLS=false
          export TOOL=cmake
          export CC=clang
          export CXX=clang++
          export CXX_STD=11
          export CFG=Debug
          export LTO=false
          export CACHE_DIR=/home/wesnoth-travis/build
          ./.github/workflows/ci-scripts/ubuntu.sh

  macos-master-release:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: macOS Release
        run: |
          export CFG=Release
          export CACHE_DIR=~/build-cache
          ./.github/workflows/ci-scripts/macos.sh

  macos-master-debug:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: macOS Debug
        run: |
          export CFG=Debug
          export CACHE_DIR=~/build-cache
          ./.github/workflows/ci-scripts/macos.sh

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: macOS-Debug
          path: |
            ~/work/wesnoth/wesnoth/projectfiles/Xcode/Wesnoth_Debug.dmg
