name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  windows-release:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: test
        shell: cmd
        run: |
          cd utils/dockerbuilds/CI/
          docker build -t wesnoth/wesnoth:windows -f Dockerfile-base-windows .

